---
title: "Database Lecture"
author: "Jerrod Anzalone"
date: "October 18, 2023"
bibliography: references.bib
format: pptx
---

## Introduction

The objective of this lecture is to introduce the fundamentals of databases, with a focus on SQLite as a lightweight and practical database engine. SQLite is widely used in various applications, including mobile apps and embedded systems, making it an invaluable tool for anyone working with data [@hipp2020].

## What is a Database?

A database is a structured collection of data that allows for efficient retrieval and manipulation. It offers a systematic way to store, manage, and retrieve information. Databases are critical in various sectors, including healthcare, finance, and academia, for tasks such as inventory management, patient record-keeping, and research data analysis [@date2006].

### Databasics

**Database:** A collection of related tables, each table with its own rows and columns 
A conceptual entity (Lab Order, Lab Result, Demographics) is represented by one table 
***Attributes*** (lab unit or lab value) are represented by one column 

Columns contain similar types of information (date and time or name) containing only one type of data (integer, varchar, binary)
Rows represent one instance of a table entry, such as a lab order or lab result or a single patient for the Demographic table


When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
